export const GET_ALL_GLOBAL_TAG_ITEM_PAGE_SUCCESS = 'GET_ALL_GLOBAL_TAG_ITEM_PAGE_SUCCESS';
export const GET_ALL_GLOBAL_TAG_ITEM_PAGE_FAIL = 'GET_ALL_GLOBAL_TAG_ITEM_PAGE_FAIL';

export const GET_ALL_GLOBAL_TAG_ITEM_SUCCESS = 'GET_ALL_GLOBAL_TAG_ITEM_SUCCESS';
export const GET_ALL_GLOBAL_TAG_ITEM_FAIL = 'GET_ALL_GLOBAL_TAG_ITEM_fail';

export const GET_GLOBAL_TAG_ITEM_TODAY_SUCCESS = 'GET_GLOBAL_TAG_ITEM_TODAY_SUCCESS';
export const GET_GLOBAL_TAG_ITEM_YESTERDAY_SUCCESS = 'GET_GLOBAL_TAG_ITEM_YESTERDAY_SUCCESS';
export const GET_GLOBAL_TAG_ITEM_LONG_SUCCESS = 'GET_GLOBAL_TAG_ITEM_LONG_SUCCESS';

export const ADD_GLOBAL_TAG_ITEM_SUCCESS = 'ADD_GLOBAL_TAG_ITEM_SUCCESS';
export const ADD_GLOBAL_TAG_ITEM_FAIL = 'ADD_GLOBAL_TAG_ITEM_FAIL';

export const EDIT_GLOBAL_TAG_ITEM_SUCCESS = 'EDIT_GLOBAL_TAG_ITEM_SUCCESS';
export const EDIT_GLOBAL_TAG_ITEM_FAIL = 'EDIT_GLOBAL_TAG_ITEM_FAIL';

export const DELETE_GLOBAL_TAG_ITEM_SUCCESS = 'DELETE_GLOBAL_TAG_ITEM_SUCCESS';
export const DELETE_GLOBAL_TAG_ITEM_FAIL = 'DELETE_GLOBAL_TAG_ITEM_FAIL';

export const RENDER_GLOBAL_TAG_ITEM_TO_EDIT = 'RENDER_GLOBAL_TAG_ITEM_TO_EDIT';

export const SHOW_GLOBAL_TAG_ITEM_LOADER = 'SHOW_GLOBAL_TAG_ITEM_LOADER';
export const REMOVE_GLOBAL_TAG_ITEM_LOADER = 'REMOVE_GLOBAL_TAG_ITEM_LOADER';