export const GET_ALL_GLOBAL_PROMPT_TAG_SUCCESS = 'GET_ALL_GLOBAL_PROMPT_TAG_SUCCESS';
export const GET_ALL_GLOBAL_PROMPT_TAG_FAIL = 'GET_ALL_GLOBAL_PROMPT_TAG_fail';

export const GET_GLOBAL_PROMPT_TAG_TODAY_SUCCESS = 'GET_GLOBAL_PROMPT_TAG_TODAY_SUCCESS';
export const GET_GLOBAL_PROMPT_TAG_YESTERDAY_SUCCESS = 'GET_GLOBAL_PROMPT_TAG_YESTERDAY_SUCCESS';
export const GET_GLOBAL_PROMPT_TAG_LONG_SUCCESS = 'GET_GLOBAL_PROMPT_TAG_LONG_SUCCESS';

export const ADD_GLOBAL_PROMPT_TAG_SUCCESS = 'ADD_GLOBAL_PROMPT_TAG_SUCCESS';
export const ADD_GLOBAL_PROMPT_TAG_FAIL = 'ADD_GLOBAL_PROMPT_TAG_FAIL';

export const EDIT_GLOBAL_PROMPT_TAG_SUCCESS = 'EDIT_GLOBAL_PROMPT_TAG_SUCCESS';
export const EDIT_GLOBAL_PROMPT_TAG_FAIL = 'EDIT_GLOBAL_PROMPT_TAG_FAIL';

export const DELETE_GLOBAL_PROMPT_TAG_SUCCESS = 'DELETE_GLOBAL_PROMPT_TAG_SUCCESS';
export const DELETE_GLOBAL_PROMPT_TAG_FAIL = 'DELETE_GLOBAL_PROMPT_TAG_FAIL';

export const RENDER_GLOBAL_PROMPT_TAG_TO_EDIT = 'RENDER_GLOBAL_PROMPT_TAG_TO_EDIT';

export const SHOW_GLOBAL_PROMPT_TAG_LOADER = 'SHOW_GLOBAL_PROMPT_TAG_LOADER';
export const REMOVE_GLOBAL_PROMPT_TAG_LOADER = 'REMOVE_GLOBAL_PROMPT_TAG_LOADER';