export const GET_ALL_GLOBAL_PROMPT_PAGE_SUCCESS = 'GET_ALL_GLOBAL_PROMPT_PAGE_SUCCESS';
export const GET_ALL_GLOBAL_PROMPT_PAGE_FAIL = 'GET_ALL_GLOBAL_PROMPT_PAGE_FAIL';

export const GET_ALL_GLOBAL_PROMPT_SUCCESS = 'GET_ALL_GLOBAL_PROMPT_SUCCESS';
export const GET_ALL_GLOBAL_PROMPT_FAIL = 'GET_ALL_GLOBAL_PROMPT_FAIL';

export const GET_GLOBAL_PROMPT_TODAY_SUCCESS = 'GET_GLOBAL_PROMPT_TODAY_SUCCESS';
export const GET_GLOBAL_PROMPT_YESTERDAY_SUCCESS = 'GET_GLOBAL_PROMPT_YESTERDAY_SUCCESS';
export const GET_GLOBAL_PROMPT_LONG_SUCCESS = 'GET_GLOBAL_PROMPT_LONG_SUCCESS';

export const ADD_GLOBAL_PROMPT_SUCCESS = 'ADD_GLOBAL_PROMPT_SUCCESS';
export const ADD_GLOBAL_PROMPT_FAIL = 'ADD_GLOBAL_PROMPT_FAIL';

export const EDIT_GLOBAL_PROMPT_SUCCESS = 'EDIT_GLOBAL_PROMPT_SUCCESS';
export const EDIT_GLOBAL_PROMPT_FAIL = 'EDIT_GLOBAL_PROMPT_FAIL';

export const DELETE_GLOBAL_PROMPT_SUCCESS = 'DELETE_GLOBAL_PROMPT_SUCCESS';
export const DELETE_GLOBAL_PROMPT_FAIL = 'DELETE_GLOBAL_PROMPT_FAIL';

export const RENDER_GLOBAL_PROMPT_TO_EDIT = 'RENDER_GLOBAL_PROMPT_TO_EDIT';

export const SHOW_GLOBAL_PROMPT_LOADER = 'SHOW_GLOBAL_PROMPT_LOADER';
export const REMOVE_GLOBAL_PROMPT_LOADER = 'REMOVE_GLOBAL_PROMPT_LOADER';