
export const GET_ALL_GLOBAL_USER_PAGE_SUCCESS = 'GET_ALL_GLOBAL_USER_PAGE_SUCCESS';
export const GET_ALL_GLOBAL_USER_PAGE_FAIL = 'GET_ALL_GLOBAL_USER_PAGE_fail';

export const GET_ALL_GLOBAL_USER_SUCCESS = 'GET_ALL_GLOBAL_USER_SUCCESS';
export const GET_ALL_GLOBAL_USER_FAIL = 'GET_ALL_GLOBAL_USER_fail';

export const GET_GLOBAL_USER_TODAY_SUCCESS = 'GET_GLOBAL_USER_TODAY_SUCCESS';
export const GET_GLOBAL_USER_YESTERDAY_SUCCESS = 'GET_GLOBAL_USER_YESTERDAY_SUCCESS';
export const GET_GLOBAL_USER_LONG_SUCCESS = 'GET_GLOBAL_USER_LONG_SUCCESS';

export const ADD_GLOBAL_USER_SUCCESS = 'ADD_GLOBAL_USER_SUCCESS';
export const ADD_GLOBAL_USER_FAIL = 'ADD_GLOBAL_USER_FAIL';

export const EDIT_GLOBAL_USER_SUCCESS = 'EDIT_GLOBAL_USER_SUCCESS';
export const EDIT_GLOBAL_USER_FAIL = 'EDIT_GLOBAL_USER_FAIL';

export const DELETE_GLOBAL_USER_SUCCESS = 'DELETE_GLOBAL_USER_SUCCESS';
export const DELETE_GLOBAL_USER_FAIL = 'DELETE_GLOBAL_USER_FAIL';

export const RENDER_GLOBAL_USER_TO_EDIT = 'RENDER_GLOBAL_USER_TO_EDIT';

export const SHOW_GLOBAL_USER_LOADER = 'SHOW_GLOBAL_USER_LOADER';
export const REMOVE_GLOBAL_USER_LOADER = 'REMOVE_GLOBAL_USER_LOADER';