
export const GET_ALL_GLOBAL_MINDSET_LIBRARY_PAGE_SUCCESS = 'GET_ALL_GLOBAL_MINDSET_LIBRARY_PAGE_SUCCESS';
export const GET_ALL_GLOBAL_MINDSET_LIBRARY_PAGE_FAIL = 'GET_ALL_GLOBAL_MINDSET_LIBRARY_PAGE_fail';

export const GET_ALL_GLOBAL_MINDSET_LIBRARY_SUCCESS = 'GET_ALL_GLOBAL_MINDSET_LIBRARY_SUCCESS';
export const GET_ALL_GLOBAL_MINDSET_LIBRARY_FAIL = 'GET_ALL_GLOBAL_MINDSET_LIBRARY_fail';

export const GET_GLOBAL_MINDSET_LIBRARY_TODAY_SUCCESS = 'GET_GLOBAL_MINDSET_LIBRARY_TODAY_SUCCESS';
export const GET_GLOBAL_MINDSET_LIBRARY_YESTERDAY_SUCCESS = 'GET_GLOBAL_MINDSET_LIBRARY_YESTERDAY_SUCCESS';
export const GET_GLOBAL_MINDSET_LIBRARY_LONG_SUCCESS = 'GET_GLOBAL_MINDSET_LIBRARY_LONG_SUCCESS';

export const ADD_GLOBAL_MINDSET_LIBRARY_SUCCESS = 'ADD_GLOBAL_MINDSET_LIBRARY_SUCCESS';
export const ADD_GLOBAL_MINDSET_LIBRARY_FAIL = 'ADD_GLOBAL_MINDSET_LIBRARY_FAIL';

export const EDIT_GLOBAL_MINDSET_LIBRARY_SUCCESS = 'EDIT_GLOBAL_MINDSET_LIBRARY_SUCCESS';
export const EDIT_GLOBAL_MINDSET_LIBRARY_FAIL = 'EDIT_GLOBAL_MINDSET_LIBRARY_FAIL';

export const DELETE_GLOBAL_MINDSET_LIBRARY_SUCCESS = 'DELETE_GLOBAL_MINDSET_LIBRARY_SUCCESS';
export const DELETE_GLOBAL_MINDSET_LIBRARY_FAIL = 'DELETE_GLOBAL_MINDSET_LIBRARY_FAIL';

export const RENDER_GLOBAL_MINDSET_LIBRARY_TO_EDIT = 'RENDER_GLOBAL_MINDSET_LIBRARY_TO_EDIT';

export const SHOW_GLOBAL_MINDSET_LIBRARY_LOADER = 'SHOW_GLOBAL_MINDSET_LIBRARY_LOADER';
export const REMOVE_GLOBAL_MINDSET_LIBRARY_LOADER = 'REMOVE_GLOBAL_MINDSET_LIBRARY_LOADER';