export const GET_ALL_GLOBAL_JOURNAL_PAGE_SUCCESS = 'GET_ALL_GLOBAL_JOURNAL_PAGE_SUCCESS';
export const GET_ALL_GLOBAL_JOURNAL_PAGE_FAIL = 'GET_ALL_GLOBAL_JOURNAL_PAGE_FAIL';

export const GET_ALL_GLOBAL_JOURNAL_SUCCESS = 'GET_ALL_GLOBAL_JOURNAL_SUCCESS';
export const GET_ALL_GLOBAL_JOURNAL_FAIL = 'GET_ALL_GLOBAL_JOURNAL_FAIL';

export const GET_GLOBAL_JOURNAL_TODAY_SUCCESS = 'GET_GLOBAL_JOURNAL_TODAY_SUCCESS';
export const GET_GLOBAL_JOURNAL_YESTERDAY_SUCCESS = 'GET_GLOBAL_JOURNAL_YESTERDAY_SUCCESS';
export const GET_GLOBAL_JOURNAL_LONG_SUCCESS = 'GET_GLOBAL_JOURNAL_LONG_SUCCESS';

export const ADD_GLOBAL_JOURNAL_SUCCESS = 'ADD_GLOBAL_JOURNAL_SUCCESS';
export const ADD_GLOBAL_JOURNAL_FAIL = 'ADD_GLOBAL_JOURNAL_FAIL';

export const EDIT_GLOBAL_JOURNAL_SUCCESS = 'EDIT_GLOBAL_JOURNAL_SUCCESS';
export const EDIT_GLOBAL_JOURNAL_FAIL = 'EDIT_GLOBAL_JOURNAL_FAIL';

export const DELETE_GLOBAL_JOURNAL_SUCCESS = 'DELETE_GLOBAL_JOURNAL_SUCCESS';
export const DELETE_GLOBAL_JOURNAL_FAIL = 'DELETE_GLOBAL_JOURNAL_FAIL';

export const RENDER_GLOBAL_JOURNAL_TO_EDIT = 'RENDER_GLOBAL_JOURNAL_TO_EDIT';

export const SHOW_GLOBAL_JOURNAL_LOADER = 'SHOW_GLOBAL_JOURNAL_LOADER';
export const REMOVE_GLOBAL_JOURNAL_LOADER = 'REMOVE_GLOBAL_JOURNAL_LOADER';